spring.cloud.stream:
  function:
    definition: producerCreate;consumerCreate
  bindings:
    producerCreate-out-0:
      destination: sending-yanki-client
    consumerCreate-in-0:
      destination: receiving-yanki-client